### ISSUE TITLE
Using `<FocusScope>` results in 'nodeToRestore' being set on Undefined on NEXT.js

### ISSUE THREAD

**Issue by rafzan** [adobe/react-spectrum#3515]
# 🐛 Bug Report 

Trying to run any `useSelect` example from https://react-spectrum.adobe.com/react-aria/useSelect.html results in "TypeError: Cannot set properties of undefined (setting 'nodeToRestore')". Searching for this error doesn't really return anything useful anywhere.

Wrapping on `SSRProvider` does nothing. Commenting FocusScope and running the application works, but you lose almost all functionality related to dismissing popups.

## 🤔 Expected Behavior

Example code should run without problems.

## 😯 Current Behavior

```
Unhandled Runtime Error
TypeError: Cannot set properties of undefined (setting 'nodeToRestore')

Call Stack
eval
../../node_modules/@react-aria/focus/dist/module.js (393:0)
commitHookEffectListMount
../../node_modules/react-dom/cjs/react-dom.development.js (23150:0)
invokeLayoutEffectMountInDEV
../../node_modules/react-dom/cjs/react-dom.development.js (25120:0)
invokeEffectsInDev
../../node_modules/react-dom/cjs/react-dom.development.js (27351:0)
commitDoubleInvokeEffectsInDEV
../../node_modules/react-dom/cjs/react-dom.development.js (27327:0)
flushPassiveEffectsImpl
../../node_modules/react-dom/cjs/react-dom.development.js (27056:0)
flushPassiveEffects
../../node_modules/react-dom/cjs/react-dom.development.js (26984:0)
commitRootImpl
../../node_modules/react-dom/cjs/react-dom.development.js (26935:0)
commitRoot
../../node_modules/react-dom/cjs/react-dom.development.js (26682:0)
performSyncWorkOnRoot
../../node_modules/react-dom/cjs/react-dom.development.js (26117:0)
flushSyncCallbacks
../../node_modules/react-dom/cjs/react-dom.development.js (12042:0)
eval
../../node_modules/react-dom/cjs/react-dom.development.js (25651:0)
```

## 🔦 Context

I'm trying to have JSX elements inside a custom `<Select>` component, just like in the StyledComponents example.
But anyone of the examples will crash.

## 💻 Code Sample

Can't seem to be able create a Next.js app on codesandbox as of now.
Locally, I just ran `yarn create-next-app --ts myApp`, copied the files to a folder and yielded the same error.

**Comment by adamstambouli** [comment]
Just came across this too and downgrading from React 18 to 17.x helps run the example.

**Comment by devongovett** [comment]
Make sure you aren't using React StrictMode

**Comment by yanndinendal** [comment]
Hi, should this issue be reopened? So we can track if this will be fixed one day? Thanks.

**Comment by snowystinger** [comment]
We're tracking StrictMode here https://github.com/adobe/react-spectrum/issues/779

**Comment by char502** [comment]
Hi, any progress on this, I've created a reusable component using datepicker for this which I'm now having to abandon because my team are not comfortable with developing an App without strict mode. 

At the very least, could it please be mentioned prominently in: https://react-spectrum.adobe.com/react-spectrum/getting-started.html so people are aware of it?

**Comment by reidbarber** [comment]
This was fixed by https://github.com/adobe/react-spectrum/pull/3878 and will be included in the next release. It is available in the nightly build now.

**Comment by char502** [comment]
@reidbarber I'm still getting the same problem with datepicker

**Comment by reidbarber** [comment]
@char502 I just confirmed locally that this is fixed in Next.js with the nightly build. Be sure you're using the nightly release in your package.json. If there is still an issue, feel free to post more information about your setup.

**Comment by char502** [comment]
@reidbarber I think I put this in the wrong group, I'm using CRA not Next.js, is there a CRA group reporting this problem and is it fixed there?

**Comment by reidbarber** [comment]
@char502 This fix is related to React Strict Mode, so it applies to both CRA and Next.js when they have strict mode enabled.

**Comment by char502** [comment]
ok, will take a look, thanks

**Comment by char502** [comment]
@reidbarber I have installed `"react-aria": "3.22.1-nightly.3690"` in storybook where there is no error (with strict mode set), however, i have tried to implement this in another repo (as this is a reusable component) and I am still getting: 
`Uncaught TypeError: Cannot set properties of undefined (setting 'nodeToRestore')`

**Comment by char502** [comment]
@reidbarber I've just implemented this and It's now working! 🎉 Thanks for letting me know re the update

**Comment by char502** [comment]
@reidbarber I have installed `"react-aria": "3.22.1-nightly.3690"`, the fix appears to work with storybook in strict mode but I have implemented the datepicker in another repo (I have used it as a reusable component) and I am still getting the error message: `Uncaught TypeError: Cannot set properties of undefined (setting 'nodeToRestore')`

**Comment by snowystinger** [comment]
That's great that you've confirmed the nightly has the fix. When we release (in the next couple weeks) that means the fix will be available for your other repo. We appreciate your patience and understanding.

**Comment by char502** [comment]
@snowystinger it didn't fix it unfortunately, I hadn't actually switched strict mode back on, when I did, the error returned so this hasn't fixed it

**Comment by snowystinger** [comment]
Sorry to hear that. Can you provide a reproduction showing the issue?

**Comment by char502** [comment]
I'm not allowed to show you our codebase, but I am using something very close to this: https://codesandbox.io/s/reverent-faraday-5nwk87?file=/src/DatePicker.js which uses a number of react-aria components.

![Screenshot 2023-02-07 at 21 51 50](https://user-images.githubusercontent.com/26301342/217374921-7afa780c-e2d2-488e-bf1a-2c0421c2f92d.png)

**Comment by char502** [comment]
I get the same error when I apply strict mode to this sandbox: https://codesandbox.io/s/lively-sound-u57mnb?file=/src/index.js

**Comment by snowystinger** [comment]
Ah, thank you for the extra info. That is not using the nightlies. I can see it is working as expected here https://codesandbox.io/s/priceless-mahavira-6y8zee. It's the same as the codesandbox you provided, just has the latest nightly installed.

One thing to note, while FocusScope has been updated to work with React StrictMode, many of the date hooks have not yet. This is a work in progress. You may find some other issues still.

**Comment by char502** [comment]
Ok, so I'll need to find an alternative. I appreciate this is a lot of work to change but a warning here: https://react-spectrum.adobe.com/react-spectrum/getting-started.html would be helpful to those that have production deadlines to meet but now have to find an alternative.

**Comment by char502** [comment]
I added the nightlies for React stately and react aria just as you have in the amended sandbox above but I'm still getting the same error message

**Comment by snowystinger** [comment]
Unfortunately, I cannot see your setup and it's not reproducing in a codesandbox currently, so I do not know what happened for you locally.

I have a guess, if you use a nightly, you must use all the nightlies of every package at the same nightly version, otherwise you can end up with duplicate packages installed. That doesn't usually result in the particular error you're seeing, but might be worth looking into.

Otherwise, we will need you to do some more debugging on your end to provide more information. For instance, there are only two places where `nodeToRestore` is set on an object in the FocusScope module. You could determine which of these is the problematic statement. 
https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/focus/src/FocusScope.tsx#L820
https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/focus/src/FocusScope.tsx#L841
Once you determine one of these, you could put in a `console.trace` and determine where it's being called from.

Other information about what version of React you're running, or what browser/OS you're on would be helpful too. Also, are you using any of the concurrent features? (they are what StrictMode is meant to help you with)

BTW. I ran our StrictTests against the date hooks, and they all appear to be working, so that is some good news for you.

**Comment by char502** [comment]
@snowystinger thanks for taking another look and for confirming re the date hooks, I appreciate it, I'm having to go with another option for now but I will take another look when I get the chance

**Comment by nimeshvaghasiya** [comment]
@char502 @snowystinger I have converted https://react-spectrum.adobe.com/react-aria/useCalendar.html to typescript components.
May be you have to use exact below versions instead of react-aria:  ^3.22.1-nightly.3690.
`
"react-aria": "3.22.1-nightly.3690",
"react-stately": "3.20.1-nightly.3690",
`
It worked with reactStrictMode: true in nextjs.

**Comment by snowystinger** [comment]
https://www.npmjs.com/package/@internationalized/date?activeTab=versions

but I'm not sure what the type error is that you're seeing. If there is one, would you mind opening a separate issue?
