### ISSUE TITLE
rac menu: unexpected placement behavior

### ISSUE THREAD

**Issue by rolanday** [adobe/react-spectrum#5186]
### Provide a general summary of the issue here

I cannot get correct placement for hamburger menu placed as bottom left corner of screen using RAC menu in first of 5 cases, where trigger button is nearest bottom left corner, and there is an animation effect being applied in other cases even though no animations have been declared.

Note: There is plenty of room for the menu to appear in all cases, so this is not (or should not) be a case of menu auto-repositioning to avoid overflowing off of screen.

Menu implemented as follows:

```
import {MenuTrigger, Button, Popover, Menu, Item} from 'react-aria-components';

export function HMenu() {
  return (<MenuTrigger>
  <Button aria-label="Menu">☰</Button>
  <Popover placement="right bottom">
    <Menu onAction={(id) => console.log(id)}>
      <Item id="open">Open</Item>
      <Item id="rename">Rename…</Item>
      <Item id="duplicate">Duplicate</Item>
      <Item id="share">Share…</Item>
      <Item id="delete">Delete…</Item>
    </Menu>
  </Popover>
</MenuTrigger>)
}
```
<img width="899" alt="Screenshot 2023-10-02 at 6 51 05 PM" src="https://github.com/adobe/react-spectrum/assets/3402123/c5a602e1-7ae2-4c51-9

https://github.com/adobe/react-spectrum/assets/3402123/fad13ad5-a7a4-462f-9fed-be4b41651eaa

e1b-7e5580a30838">

### 🤔 Expected Behavior?

When menu appears, expect to see left edge of popup aligned to right of trigger button, and bottom aligned with bottom of button, in all cases provided (see repro /video) and w/o animation.

### 😯 Current Behavior

Varying behavior depending on location of trigger button.

### 🖥️ Steps to Reproduce

Repo here: https://github.com/rolanday/rac-menu-placement

1. Clone
2. Install deps
3. `npm run dev`
4. Click menus, observe behaviors

### Version

1.0.0-beta.1 (RAC)

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

macOS (Sonoma, v14.0)

**Comment by yihuiliao** [comment]
Seems like for the first case, the maxHeight is getting set to 0px which is what is causing its weird placement. We might need to revisit our calculations for [getMaxHeight](https://github.com/adobe/react-spectrum/blob/7c7e84624629d4963ff500cbd75a3412cb3a9e8f/packages/%40react-aria/overlays/src/calculatePosition.ts#L249). Our current stories for `useOverlayPosition` seem to test when position is relative, maybe would be good to add when position is absolute. 

As for the animation, that is definitely weird and will need to investigate that more. I also made a [codesandbox](https://codesandbox.io/s/musing-drake-3nrf44?file=/src/App.js) very similar to yours which also demonstrates the animation you’re seeing as well. I thought it could have been related to Tailwind but seems that’s not the case.

**Comment by rolanday** [comment]
@yihuiliao , appreciate your taking a look at this. FYI, I used absolute for repro only for ease of showing the various placement cases. My actual  impl uses flex-box and align to achieve similar placement to the second case (bottom left placement). Can also confirm not related to Tailwind (I had previously ruled that out, also suspecting may be related. Thanks again!

**Comment by rolanday** [comment]
Hi @devongovett , @yihuiliao , checking in on this since I'm at a point where will need to finish hooks implementation instead of using RAC if not resolved soon. I saw RAC 1.0 may be soon, and this should be P0 to fix IMO since placing hamburger menu at bottom corner is common design pattern.

Thanks!

-Roland.

**Comment by LFDanLu** [comment]
@rolanday We ran into something similar for our SubMenu implementation in React Spectrum and are tracking those two issues via https://github.com/orgs/adobe/projects/19/views/20?pane=issue&itemId=43393367 and https://github.com/orgs/adobe/projects/19/views/20?pane=issue&itemId=45014178. Unfortunately these fixes will not make it for the RAC 1.0 release but we hope to pick them up soon in our next sprint after the holiday break.

**Comment by rolanday** [comment]
@LFDanLu , thanks for letting me know. Much appreciated.

**Comment by LFDanLu** [comment]
@rolanday I believe this has been fixed by https://github.com/adobe/react-spectrum/pull/5660. I verified locally in your example repo with the [1.0.2-nightly.4419](https://www.npmjs.com/package/react-aria-components/v/1.0.2-nightly.4419). Feel free to try that nightly yourself or when this fix goes out with the next release (roughly at/near the start of next month).  Closing as resolved but feel free to reopen if something still breaks.

**Comment by rolanday** [comment]
Hi @LFDanLu , thanks for the follow-up! I'm still seeing the issue on my end, but will wait for the next release and, if I still see the issue with it, then will work on providing an alternate repro. I should add that the "top *" placements work as expected (1.0.2-nightly.4419 and previous builds), but all other placements result in popover shrinking in heigh (w/ scrollbar) so stay in view instead of clipping (as opposed to adjusting placement).

**Comment by LFDanLu** [comment]
> but all other placements result in popover shrinking in heigh (w/ scrollbar) so stay in view instead of clipping (as opposed to adjusting placement)

Just to make sure, you are saying the popovers are adjusting their max height instead of just being cut off by the boundaries of the screen? Not entirely certain what is meant by clipping here, do you happen to have a screenshot to share?
