### ISSUE TITLE
Example for RAC Select with complex items is missing

### ISSUE THREAD

**Issue by agos** [adobe/react-spectrum#6873]
### 🙋 Documentation Request

The documentation of RAC Select component mentions an example with "complex items", but [the link](https://react-spectrum.adobe.com/react-aria/Select.html#complex-items) points to a section which does not exist.

**Comment by LFDanLu** [comment]
Thank you for catching this, that link should probably point to https://react-spectrum.adobe.com/react-aria/Select.html#text-slots.

**Comment by parthsali** [comment]
Hi @LFDanLu,

I would like to work on this issue. Could you please assign it to me or let me know if there are any specific requirements or guidelines I should follow?

Thank you!

**Comment by LFDanLu** [comment]
Ah whoops, I just realized I conflated your comment from the other issue with this one. Definitely feel free to pick up this issue, the line in question that needs to be modified is https://github.com/adobe/react-spectrum/blob/69cc4456cc400bce082e21d1fc5f49359e9161b9/packages/react-aria-components/docs/Select.mdx?plain=1#L1064 and as mentioned above should now point to https://react-spectrum.adobe.com/react-aria/Select.html#text-slots instead. Lemme know if you run into any issues getting the docs to build locally!

**Comment by snowystinger** [comment]
Looks like you are on a windows machine? If so, there's a branch that will get you up and running. We're in the middle of reviewing it and should have it merged soon https://github.com/adobe/react-spectrum/pull/6313#issue-2274410623

**Comment by parthsali** [comment]
Thank you for the quick response @snowystinger! Yes, I’m on a Windows machine. I’ll keep an eye out for the branch and try again once it’s merged. If there’s anything else I can help with in the meantime, please let me know!

**Comment by snowystinger** [comment]
you could also base your branch off of that one, then you don't have to wait

**Comment by LFDanLu** [comment]
@parthsali I've merged in #6313, but that fix was mainly around storybook, didn't think to test the local docs build. Mind giving it a shot? I'll try it tomorrow when I'm back home and have access to my windows machine

**Comment by parthsali** [comment]
@LFDanLu Thanks for the update! I synced my repo, pulled the latest changes, and rebuilt the entire project, but I'm still not able to run it due to the same error. Let me know if there's anything else I can do to help troubleshoot this.
